module.exports = {
    plugins: ["stylelint-order"],
    rules: {
        "order/properties-order": [
            [
                // Positioning & layout
                "position",
                "top",
                "right",
                "bottom",
                "left",
                "z-index",
                "display",
                "flex",
                "flex-direction",
                "flex-wrap",
                "flex-flow",
                "flex-grow",
                "flex-shrink",
                "flex-basis",
                "justify-content",
                "align-items",
                "align-content",
                "order",
                "grid",
                "grid-template",
                "grid-template-rows",
                "grid-template-columns",
                "grid-row",
                "grid-column",
                "float",
                "clear",
                "box-sizing",

                // Box model
                "width",
                "min-width",
                "max-width",
                "height",
                "min-height",
                "max-height",
                "margin",
                "border",
                "border-radius",
                "padding",
                "overflow",

                // Typography
                "font",
                "font-family",
                "font-size",
                "font-weight",
                "line-height",
                "text-align",
                "text-decoration",
                "text-transform",
                "letter-spacing",
                "white-space",

                // Visual
                "color",
                "background",
                "background-color",
                "background-image",
                "box-shadow",
                "opacity",
                "transform",
                "transition",
                "animation",

                // Misc
                "cursor",
                "pointer-events",
                "user-select",
            ],
            { unspecified: "bottomAlphabetical" },
        ],
    },
};