export { handleLoadWordDetail } from "./handleLoadWordDetail.js";
export { renderWordDetail } from "./renderWordDetail.js";
export { renderAdjectiveAgreementTable } from "./renderAdjectiveAgreementTable.js";
export { renderConjugationTable } from "./renderConjugationTable.js";
export { renderDeclensionTable } from "./renderDeclensionTable.js";
export { renderDefinitions } from "./renderDefinitions.js";
export { renderInflectionType } from "./renderInflectionType.js";
export { renderLemmaHeader } from "./renderLemmaHeader.js";
export { renderPrincipalParts } from "./renderPrincipalParts.js";
